BOT_TOKEN = "8920966526:AAEvCZr9dWR8vQgLAWz47dXsxvAV-Lg5M3g"
GIGACHAT_CREDENTIALS = "MDFhMGNiMjAtODFjYi03MDUwLThlZjktMzQwYjQ4M2NmNGViOjBmNzRhNzU2LWI0YmMtNDNjZS05NDY2LTc2NTFmODc3MGMyOA=="
GIGACHAT_SCOPE = "GIGACHAT_API_PERS"
GIGACHAT_MODEL = "GigaChat-2"
FREE_DAILY_LIMIT = 10
PREMIUM_PRICE_STARS = 100
AI_MARKER = "🤖 Сгенерировано ИИ"